export const FETCH_STATE_DATA = 'FETCH_STATE_DATA';
export const SET_CURRENT_MARKET = 'SET_CURRENT_MARKET';
export const FETCH_EXPERTS = 'FETCH_EXPERTS';
export const SET_CURRENT_EXPERT = 'CURRENT_EXPERT';
